# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sonar-3d-15-protocol.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sonar-3d-15-protocol.proto',
  package='waterlinked.sonar.protocol',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1asonar-3d-15-protocol.proto\x12\x1awaterlinked.sonar.protocol\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"+\n\x06Packet\x12!\n\x03msg\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\"L\n\x06Header\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0bsequence_id\x18\x02 \x01(\r\"\xa7\x02\n\x15\x42itmapImageGreyscale8\x12\x32\n\x06header\x18\x01 \x01(\x0b\x32\".waterlinked.sonar.protocol.Header\x12\x16\n\x0espeed_of_sound\x18\x02 \x01(\x02\x12\r\n\x05range\x18\x03 \x01(\x02\x12\x11\n\tfrequency\x18\x04 \x01(\r\x12\x39\n\x04type\x18\x05 \x01(\x0e\x32+.waterlinked.sonar.protocol.BitmapImageType\x12\r\n\x05width\x18\x06 \x01(\r\x12\x0e\n\x06height\x18\x07 \x01(\r\x12\x16\n\x0ehorizontal_fov\x18\x08 \x01(\x02\x12\x14\n\x0cvertical_fov\x18\t \x01(\x02\x12\x18\n\x10image_pixel_data\x18\n \x01(\x0c\"\x95\x02\n\nRangeImage\x12\x32\n\x06header\x18\x01 \x01(\x0b\x32\".waterlinked.sonar.protocol.Header\x12\x16\n\x0espeed_of_sound\x18\x02 \x01(\x02\x12\r\n\x05range\x18\x03 \x01(\x02\x12\x11\n\tfrequency\x18\x04 \x01(\r\x12\x1b\n\x13n_pixels_horizontal\x18\x05 \x01(\r\x12\x19\n\x11n_pixels_vertical\x18\x06 \x01(\r\x12\x16\n\x0e\x66ov_horizontal\x18\x07 \x01(\x02\x12\x14\n\x0c\x66ov_vertical\x18\x08 \x01(\x02\x12\x19\n\x11image_pixel_scale\x18\t \x01(\x02\x12\x18\n\x10image_pixel_data\x18\n \x03(\r*>\n\x0f\x42itmapImageType\x12\x19\n\x15SIGNAL_STRENGTH_IMAGE\x10\x00\x12\x10\n\x0cSHADED_IMAGE\x10\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])

_BITMAPIMAGETYPE = _descriptor.EnumDescriptor(
  name='BitmapImageType',
  full_name='waterlinked.sonar.protocol.BitmapImageType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SIGNAL_STRENGTH_IMAGE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHADED_IMAGE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=819,
  serialized_end=881,
)
_sym_db.RegisterEnumDescriptor(_BITMAPIMAGETYPE)

BitmapImageType = enum_type_wrapper.EnumTypeWrapper(_BITMAPIMAGETYPE)
SIGNAL_STRENGTH_IMAGE = 0
SHADED_IMAGE = 1



_PACKET = _descriptor.Descriptor(
  name='Packet',
  full_name='waterlinked.sonar.protocol.Packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='waterlinked.sonar.protocol.Packet.msg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=161,
)


_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='waterlinked.sonar.protocol.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='waterlinked.sonar.protocol.Header.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sequence_id', full_name='waterlinked.sonar.protocol.Header.sequence_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=239,
)


_BITMAPIMAGEGREYSCALE8 = _descriptor.Descriptor(
  name='BitmapImageGreyscale8',
  full_name='waterlinked.sonar.protocol.BitmapImageGreyscale8',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='waterlinked.sonar.protocol.BitmapImageGreyscale8.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed_of_sound', full_name='waterlinked.sonar.protocol.BitmapImageGreyscale8.speed_of_sound', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='range', full_name='waterlinked.sonar.protocol.BitmapImageGreyscale8.range', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frequency', full_name='waterlinked.sonar.protocol.BitmapImageGreyscale8.frequency', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='waterlinked.sonar.protocol.BitmapImageGreyscale8.type', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='waterlinked.sonar.protocol.BitmapImageGreyscale8.width', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='waterlinked.sonar.protocol.BitmapImageGreyscale8.height', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='horizontal_fov', full_name='waterlinked.sonar.protocol.BitmapImageGreyscale8.horizontal_fov', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vertical_fov', full_name='waterlinked.sonar.protocol.BitmapImageGreyscale8.vertical_fov', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_pixel_data', full_name='waterlinked.sonar.protocol.BitmapImageGreyscale8.image_pixel_data', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=537,
)


_RANGEIMAGE = _descriptor.Descriptor(
  name='RangeImage',
  full_name='waterlinked.sonar.protocol.RangeImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='waterlinked.sonar.protocol.RangeImage.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed_of_sound', full_name='waterlinked.sonar.protocol.RangeImage.speed_of_sound', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='range', full_name='waterlinked.sonar.protocol.RangeImage.range', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frequency', full_name='waterlinked.sonar.protocol.RangeImage.frequency', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n_pixels_horizontal', full_name='waterlinked.sonar.protocol.RangeImage.n_pixels_horizontal', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n_pixels_vertical', full_name='waterlinked.sonar.protocol.RangeImage.n_pixels_vertical', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fov_horizontal', full_name='waterlinked.sonar.protocol.RangeImage.fov_horizontal', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fov_vertical', full_name='waterlinked.sonar.protocol.RangeImage.fov_vertical', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_pixel_scale', full_name='waterlinked.sonar.protocol.RangeImage.image_pixel_scale', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image_pixel_data', full_name='waterlinked.sonar.protocol.RangeImage.image_pixel_data', index=9,
      number=10, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=540,
  serialized_end=817,
)

_PACKET.fields_by_name['msg'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_HEADER.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_BITMAPIMAGEGREYSCALE8.fields_by_name['header'].message_type = _HEADER
_BITMAPIMAGEGREYSCALE8.fields_by_name['type'].enum_type = _BITMAPIMAGETYPE
_RANGEIMAGE.fields_by_name['header'].message_type = _HEADER
DESCRIPTOR.message_types_by_name['Packet'] = _PACKET
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['BitmapImageGreyscale8'] = _BITMAPIMAGEGREYSCALE8
DESCRIPTOR.message_types_by_name['RangeImage'] = _RANGEIMAGE
DESCRIPTOR.enum_types_by_name['BitmapImageType'] = _BITMAPIMAGETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Packet = _reflection.GeneratedProtocolMessageType('Packet', (_message.Message,), {
  'DESCRIPTOR' : _PACKET,
  '__module__' : 'sonar_3d_15_protocol_pb2'
  # @@protoc_insertion_point(class_scope:waterlinked.sonar.protocol.Packet)
  })
_sym_db.RegisterMessage(Packet)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {
  'DESCRIPTOR' : _HEADER,
  '__module__' : 'sonar_3d_15_protocol_pb2'
  # @@protoc_insertion_point(class_scope:waterlinked.sonar.protocol.Header)
  })
_sym_db.RegisterMessage(Header)

BitmapImageGreyscale8 = _reflection.GeneratedProtocolMessageType('BitmapImageGreyscale8', (_message.Message,), {
  'DESCRIPTOR' : _BITMAPIMAGEGREYSCALE8,
  '__module__' : 'sonar_3d_15_protocol_pb2'
  # @@protoc_insertion_point(class_scope:waterlinked.sonar.protocol.BitmapImageGreyscale8)
  })
_sym_db.RegisterMessage(BitmapImageGreyscale8)

RangeImage = _reflection.GeneratedProtocolMessageType('RangeImage', (_message.Message,), {
  'DESCRIPTOR' : _RANGEIMAGE,
  '__module__' : 'sonar_3d_15_protocol_pb2'
  # @@protoc_insertion_point(class_scope:waterlinked.sonar.protocol.RangeImage)
  })
_sym_db.RegisterMessage(RangeImage)


# @@protoc_insertion_point(module_scope)
